/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import audio.AePlayWave;
import audio.PlayAudio;
import java.awt.Color;
import java.net.URISyntaxException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Daniel Aguilar
 */
public class CatGame extends javax.swing.JFrame {

    int isTurno;

    /**
     * Creates new form CatGame
     */
    public CatGame() {
        initComponents();
        isTurno = 1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnReset = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnStart = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnCel1 = new javax.swing.JButton();
        btnCel2 = new javax.swing.JButton();
        btnCel3 = new javax.swing.JButton();
        btnCel4 = new javax.swing.JButton();
        btnCel5 = new javax.swing.JButton();
        btnCel6 = new javax.swing.JButton();
        btnCel7 = new javax.swing.JButton();
        btnCel8 = new javax.swing.JButton();
        btnCel9 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtPlayer1 = new javax.swing.JTextField();
        txtPlayer2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Game ");
        setPreferredSize(new java.awt.Dimension(1100, 700));

        jLabel1.setBackground(new java.awt.Color(102, 102, 102));
        jLabel1.setFont(new java.awt.Font("Magneto", 2, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cat.jpg"))); // NOI18N
        jLabel1.setText("            Cat Game ");
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 153, 255)));

        btnReset.setText("Reset");
        btnReset.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnExit.setText("Exit");
        btnExit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        btnStart.setText("Start");
        btnStart.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnReset, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
            .addComponent(btnExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnStart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(btnReset)
                .addGap(27, 27, 27)
                .addComponent(btnExit)
                .addGap(33, 33, 33)
                .addComponent(btnStart)
                .addContainerGap(233, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.LINE_END);

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setLayout(new java.awt.GridLayout(3, 3));

        btnCel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/calarius.jpg"))); // NOI18N
        btnCel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCel1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnCel1);

        btnCel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/calarius.jpg"))); // NOI18N
        btnCel2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCel2ActionPerformed(evt);
            }
        });
        jPanel2.add(btnCel2);

        btnCel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/calarius.jpg"))); // NOI18N
        btnCel3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCel3ActionPerformed(evt);
            }
        });
        jPanel2.add(btnCel3);

        btnCel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/calarius.jpg"))); // NOI18N
        btnCel4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCel4ActionPerformed(evt);
            }
        });
        jPanel2.add(btnCel4);

        btnCel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/calarius.jpg"))); // NOI18N
        btnCel5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCel5ActionPerformed(evt);
            }
        });
        jPanel2.add(btnCel5);

        btnCel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/calarius.jpg"))); // NOI18N
        btnCel6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCel6ActionPerformed(evt);
            }
        });
        jPanel2.add(btnCel6);

        btnCel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/calarius.jpg"))); // NOI18N
        btnCel7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCel7ActionPerformed(evt);
            }
        });
        jPanel2.add(btnCel7);

        btnCel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/calarius.jpg"))); // NOI18N
        btnCel8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCel8ActionPerformed(evt);
            }
        });
        jPanel2.add(btnCel8);

        btnCel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/calarius.jpg"))); // NOI18N
        btnCel9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCel9ActionPerformed(evt);
            }
        });
        jPanel2.add(btnCel9);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 102, 255)));

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 0, 102));
        jLabel3.setText("Player 1 ");

        jLabel4.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 0, 153));
        jLabel4.setText("Player 2");

        txtPlayer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPlayer1ActionPerformed(evt);
            }
        });

        txtPlayer2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtPlayer2MouseEntered(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPlayer1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(174, 174, 174)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                    .addComponent(txtPlayer2))
                .addContainerGap(56, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtPlayer1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPlayer2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /*Este metodo restaura todos los botones, inserta un imagen de incio 
    y anula el valor en la propiedad actionCommand*/
    private void restaura() {
        btnCel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/calarius.jpg")));
        btnCel1.setActionCommand("");
        btnCel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/calarius.jpg")));
        btnCel2.setActionCommand("");
        btnCel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/calarius.jpg")));
        btnCel3.setActionCommand("");
        btnCel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/calarius.jpg")));
        btnCel4.setActionCommand("");
        btnCel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/calarius.jpg")));
        btnCel5.setActionCommand("");
        btnCel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/calarius.jpg")));
        btnCel6.setActionCommand("");
        btnCel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/calarius.jpg")));
        btnCel7.setActionCommand("");
        btnCel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/calarius.jpg")));
        btnCel8.setActionCommand("");
        btnCel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/calarius.jpg")));
        btnCel9.setActionCommand("");
    }
    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        try {
            AePlayWave aw;
            URL url = PlayAudio.class.getResource("/audio/cats.wav");
            aw = new AePlayWave(url);
            aw.start();
        } catch (URISyntaxException ex) {
            Logger.getLogger(PlayAudio.class.getName()).log(Level.SEVERE, null, ex);
        }
        restaura();
        txtPlayer1.setText("");
        txtPlayer2.setText("");
        JOptionPane.showMessageDialog(null, "Presiona el botón ''Start'' para comensar el juego.");
    }//GEN-LAST:event_btnResetActionPerformed
    /*Reproduce un sonido unsado en cada boton*/
    private void miau() {
        // TODO add your handling code here:
        try {
            AePlayWave aw;
            URL url = PlayAudio.class.getResource("/audio/boing.wav");
            aw = new AePlayWave(url);
            aw.start();
        } catch (URISyntaxException ex) {
            Logger.getLogger(PlayAudio.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /*Metodo que reproduce un sonido al insertar datos en los nombres de los jugadores*/
    private void insert() {
        try {
            AePlayWave aw;
            URL url = PlayAudio.class.getResource("/audio/insert_coin.wav");
            aw = new AePlayWave(url);
            aw.start();
        } catch (URISyntaxException ex) {
            Logger.getLogger(PlayAudio.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /*Metod que reproduce un sonido al iniciar el juego*/
    private void intro() {
        try {
            AePlayWave aw;
            URL url = PlayAudio.class.getResource("/audio/go.wav");
            aw = new AePlayWave(url);
            aw.start();
        } catch (URISyntaxException ex) {
            Logger.getLogger(PlayAudio.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /*Metodo que reproduce un sonido para el ganador*/
    private void gana() {
        try {
            AePlayWave aw;
            URL url = PlayAudio.class.getResource("/audio/TaDa.wav");
            aw = new AePlayWave(url);
            aw.start();
        } catch (URISyntaxException ex) {
            Logger.getLogger(PlayAudio.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /*Reproduce un sonido de error y nuestra un mesaje*/
    private void falla() {
        try {
            AePlayWave aw;
            URL url = PlayAudio.class.getResource("/audio/fail.wav");
            aw = new AePlayWave(url);
            aw.start();
            JOptionPane.showMessageDialog(null, "¡Elige otra casilla!");
        } catch (URISyntaxException ex) {
            Logger.getLogger(PlayAudio.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /*Reproduce un sonido de despedida*/
    private void byeBye() {
        try {
            AePlayWave aw;
            URL url = PlayAudio.class.getResource("/audio/bye.wav");
            aw = new AePlayWave(url);
            aw.start();
        } catch (URISyntaxException ex) {
            Logger.getLogger(PlayAudio.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /*Metodo que verifica el ganador de tres formas horizontal, vertical y diagonal.
     Muestra un mesaje de felicidades con el nombre del ganador y llama al metodo gana();.
     */
    private void verificaGanador() {
        //Horizontales
        if (btnCel1.getActionCommand() == "1" && btnCel2.getActionCommand() == "1" && btnCel3.getActionCommand() == "1") {
            gana();
            JOptionPane.showMessageDialog(null, "¡Felicidades ha ganado:" + txtPlayer1.getText() + " !");
        }
        if (btnCel4.getActionCommand() == "1" && btnCel5.getActionCommand() == "1" && btnCel6.getActionCommand() == "1") {
            gana();
            JOptionPane.showMessageDialog(null, "¡Felicidades ha ganado:" + txtPlayer1.getText() + " !");
        }
        if (btnCel7.getActionCommand() == "1" && btnCel8.getActionCommand() == "1" && btnCel9.getActionCommand() == "1") {
            gana();
            JOptionPane.showMessageDialog(null, "¡Felicidades ha ganado:" + txtPlayer1.getText() + " !");
        }
        if (btnCel1.getActionCommand() == "2" && btnCel2.getActionCommand() == "2" && btnCel3.getActionCommand() == "2") {
            gana();
            JOptionPane.showMessageDialog(null, "¡Felicidades ha ganado:" + txtPlayer2.getText() + " !");
        }
        if (btnCel4.getActionCommand() == "2" && btnCel5.getActionCommand() == "2" && btnCel6.getActionCommand() == "2") {
            gana();
            JOptionPane.showMessageDialog(null, "¡Felicidades ha ganado:" + txtPlayer2.getText() + " !");
        }
        if (btnCel7.getActionCommand() == "2" && btnCel8.getActionCommand() == "2" && btnCel9.getActionCommand() == "2") {
            gana();
            JOptionPane.showMessageDialog(null, "¡Felicidades ha ganado:" + txtPlayer2.getText() + " !");
        }
        //Verticales
        if (btnCel1.getActionCommand() == "1" && btnCel4.getActionCommand() == "1" && btnCel7.getActionCommand() == "1") {
            gana();
            JOptionPane.showMessageDialog(null, "¡Felicidades ha ganado:" + txtPlayer1.getText() + " !");
        }
        if (btnCel2.getActionCommand() == "1" && btnCel5.getActionCommand() == "1" && btnCel8.getActionCommand() == "1") {
            gana();
            JOptionPane.showMessageDialog(null, "¡Felicidades ha ganado:" + txtPlayer1.getText() + " !");
        }
        if (btnCel3.getActionCommand() == "1" && btnCel6.getActionCommand() == "1" && btnCel9.getActionCommand() == "1") {
            gana();
            JOptionPane.showMessageDialog(null, "¡Felicidades ha ganado:" + txtPlayer1.getText() + " !");
        }
        if (btnCel1.getActionCommand() == "2" && btnCel4.getActionCommand() == "2" && btnCel7.getActionCommand() == "2") {
            gana();
            JOptionPane.showMessageDialog(null, "¡Felicidades ha ganado:" + txtPlayer2.getText() + " !");
        }
        if (btnCel2.getActionCommand() == "2" && btnCel5.getActionCommand() == "2" && btnCel8.getActionCommand() == "2") {
            gana();
            JOptionPane.showMessageDialog(null, "¡Felicidades ha ganado:" + txtPlayer2.getText() + " !");
        }
        if (btnCel3.getActionCommand() == "2" && btnCel6.getActionCommand() == "2" && btnCel9.getActionCommand() == "2") {
            gana();
            JOptionPane.showMessageDialog(null, "¡Felicidades ha ganado:" + txtPlayer2.getText() + " !");
        }
        //Oblicuas
        if (btnCel1.getActionCommand() == "1" && btnCel5.getActionCommand() == "1" && btnCel9.getActionCommand() == "1") {
            gana();
            JOptionPane.showMessageDialog(null, "¡Felicidades ha ganado:" + txtPlayer1.getText() + " !");
        }
        if (btnCel3.getActionCommand() == "1" && btnCel5.getActionCommand() == "1" && btnCel7.getActionCommand() == "1") {
            gana();
            JOptionPane.showMessageDialog(null, "¡Felicidades ha ganado:" + txtPlayer1.getText() + " !");
        }
        if (btnCel1.getActionCommand() == "2" && btnCel5.getActionCommand() == "2" && btnCel9.getActionCommand() == "2") {
            gana();
            JOptionPane.showMessageDialog(null, "¡Felicidades ha ganado:" + txtPlayer2.getText() + " !");
        }
        if (btnCel3.getActionCommand() == "2" && btnCel5.getActionCommand() == "2" && btnCel7.getActionCommand() == "2") {
            gana();
            JOptionPane.showMessageDialog(null, "¡Felicidades ha ganado:" + txtPlayer2.getText() + " !");
        }
    }//Fin verificaGanador
    
    /*Metodo que verifica la propiedad actionCommand para checar el empate*/
    private void verEmpate() {
        if ((btnCel1.getActionCommand() == "1" || btnCel1.getActionCommand() == "2")
                && (btnCel2.getActionCommand() == "1" || btnCel2.getActionCommand() == "2")
                && (btnCel3.getActionCommand() == "1" || btnCel3.getActionCommand() == "2")
                && (btnCel4.getActionCommand() == "1" || btnCel4.getActionCommand() == "2")
                && (btnCel5.getActionCommand() == "1" || btnCel5.getActionCommand() == "2")
                && (btnCel6.getActionCommand() == "1" || btnCel6.getActionCommand() == "2")
                && (btnCel7.getActionCommand() == "1" || btnCel7.getActionCommand() == "2")
                && (btnCel8.getActionCommand() == "1" || btnCel8.getActionCommand() == "2")
                && (btnCel9.getActionCommand() == "1" || btnCel9.getActionCommand() == "2")) {
            JOptionPane.showMessageDialog(null, "¡Juego Empatado, presiona ''Reset'' para restablecer el juego!");
        }
         
    }

    private void btnCel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCel1ActionPerformed
        miau();
        if (btnCel1.getActionCommand().isEmpty()) {
            if (isTurno == 1) {
                btnCel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/x.png")));
                btnCel1.setActionCommand("1");
                this.verificaGanador();
                isTurno = 2;
                verEmpate();
            } else {
                btnCel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/o.png")));
                btnCel1.setActionCommand("2");
                isTurno = 1;
                this.verificaGanador();
                verEmpate();
            }
        } else {
            falla();
        }
    }//GEN-LAST:event_btnCel1ActionPerformed

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        insert();
        String p1 = JOptionPane.showInputDialog("Ingresa Nombre del Jugador 1");
        txtPlayer1.setText(p1);
        insert();
        String p2 = JOptionPane.showInputDialog("Ingresa Nombre del Jugador 2");
        txtPlayer2.setText(p2);
        intro();

        // txtPlayer1.requestFocus();
    }//GEN-LAST:event_btnStartActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        String resp = "";
        byeBye();
        resp = JOptionPane.showInputDialog(null, "¿Esta seguro que deseas salir?"
                + "\n(SI/NO)");
        if (resp.equalsIgnoreCase("SI")) {
            System.exit(0);
        } else {

        }
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnCel2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCel2ActionPerformed
        // TODO add your handling code here:
        miau();
        if (btnCel2.getActionCommand().isEmpty()) {

            if (isTurno == 1) {
                btnCel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/x.png")));
                btnCel2.setActionCommand("1");
                this.verificaGanador();
                isTurno = 2;
                verEmpate();
            } else {
                btnCel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/o.png")));
                btnCel2.setActionCommand("2");
                isTurno = 1;
                this.verificaGanador();
                verEmpate();
            }
        } else {
            falla();
        }
    }//GEN-LAST:event_btnCel2ActionPerformed

    private void btnCel3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCel3ActionPerformed
        // TODO add your handling code here:
        miau();
        if (btnCel3.getActionCommand().isEmpty()) {

            if (isTurno == 1) {
                btnCel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/x.png")));
                btnCel3.setActionCommand("1");
                isTurno = 2;
                this.verificaGanador();
                verEmpate();
            } else {
                btnCel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/o.png")));
                btnCel3.setActionCommand("2");
                isTurno = 1;
                this.verificaGanador();
                verEmpate();
            }
        } else {
            falla();
        }
    }//GEN-LAST:event_btnCel3ActionPerformed

    private void btnCel4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCel4ActionPerformed
        miau();
        if (btnCel4.getActionCommand().isEmpty()) {

            if (isTurno == 1) {
                btnCel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/x.png")));
                btnCel4.setActionCommand("1");
                isTurno = 2;
                this.verificaGanador();
                verEmpate();
            } else {
                btnCel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/o.png")));
                btnCel4.setActionCommand("2");
                isTurno = 1;
                this.verificaGanador();
                 verEmpate();
            }
        } else {
            falla();
        }
    }//GEN-LAST:event_btnCel4ActionPerformed

    private void btnCel5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCel5ActionPerformed
        // TODO add your handling code here:
        miau();
        if (btnCel5.getActionCommand().isEmpty()) {

            if (isTurno == 1) {
                btnCel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/x.png")));
                btnCel5.setActionCommand("1");
                isTurno = 2;
                this.verificaGanador();
                 verEmpate();
            } else {
                btnCel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/o.png")));
                btnCel5.setActionCommand("2");
                isTurno = 1;
                this.verificaGanador();
                 verEmpate();
            }
        } else {
            falla();
        }
    }//GEN-LAST:event_btnCel5ActionPerformed

    private void btnCel6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCel6ActionPerformed
        miau();
        if (btnCel6.getActionCommand().isEmpty()) {
            if (isTurno == 1) {
                btnCel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/x.png")));
                btnCel6.setActionCommand("1");
                isTurno = 2;
                this.verificaGanador();
                verEmpate();
            } else {
                btnCel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/o.png")));
                btnCel6.setActionCommand("2");
                isTurno = 1;
                this.verificaGanador();
                verEmpate();
            }
        } else {
            falla();
        }
    }//GEN-LAST:event_btnCel6ActionPerformed

    private void btnCel7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCel7ActionPerformed
        // TODO add your handling code here:
        miau();
        if (btnCel7.getActionCommand().isEmpty()) {
            if (isTurno == 1) {
                btnCel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/x.png")));
                btnCel7.setActionCommand("1");
                isTurno = 2;
                this.verificaGanador();
                 verEmpate();
            } else {
                btnCel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/o.png")));
                btnCel7.setActionCommand("2");
                isTurno = 1;
                this.verificaGanador();
                 verEmpate();
            }
        } else {
            falla();
        }
    }//GEN-LAST:event_btnCel7ActionPerformed

    private void btnCel8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCel8ActionPerformed
        // TODO add your handling code here:
        miau();
        if (btnCel8.getActionCommand().isEmpty()) {

            if (isTurno == 1) {
                btnCel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/x.png")));
                btnCel8.setActionCommand("1");
                isTurno = 2;
                this.verificaGanador();
                 verEmpate();
            } else {
                btnCel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/o.png")));
                btnCel8.setActionCommand("2");
                isTurno = 1;
                this.verificaGanador();
                 verEmpate();
            }
        } else {
            falla();
        }
    }//GEN-LAST:event_btnCel8ActionPerformed

    private void btnCel9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCel9ActionPerformed
        // TODO add your handling code here:
        miau();
        if (btnCel9.getActionCommand().isEmpty()) {

            if (isTurno == 1) {
                btnCel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/x.png")));
                btnCel9.setActionCommand("1");
                isTurno = 2;
                this.verificaGanador();
                 verEmpate();
            } else {
                btnCel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/o.png")));
                btnCel9.setActionCommand("2");
                isTurno = 1;
                this.verificaGanador();
                verEmpate();
            }
        } else {
            falla();
        }
    }//GEN-LAST:event_btnCel9ActionPerformed

    private void txtPlayer2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPlayer2MouseEntered
        // TODO add your handling code here:z
    }//GEN-LAST:event_txtPlayer2MouseEntered

    private void txtPlayer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPlayer1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPlayer1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CatGame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CatGame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CatGame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CatGame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CatGame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCel1;
    private javax.swing.JButton btnCel2;
    private javax.swing.JButton btnCel3;
    private javax.swing.JButton btnCel4;
    private javax.swing.JButton btnCel5;
    private javax.swing.JButton btnCel6;
    private javax.swing.JButton btnCel7;
    private javax.swing.JButton btnCel8;
    private javax.swing.JButton btnCel9;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnStart;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txtPlayer1;
    private javax.swing.JTextField txtPlayer2;
    // End of variables declaration//GEN-END:variables
}
